dist: trusty
language: java

addons:
  sonarcloud:
    organization: "mogikanen9-github"
    
jdk:
- oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN}    
